import { Inter } from "next/font/google";
import Explorer from "./component/explorer/page";
import Sidebar from "./component/sidebar/sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="">
        <Sidebar />
        <body className={inter.className}>{children}</body>
        <Explorer />
      </div>
    </html>
  );
}
