import { Inter } from "next/font/google";
import Explorer from "./component/explorer/page";
import Sidebar from "./component/sidebar/sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="root-layout flex">
        <Explorer />
        <body className={inter.className}>{children}</body>
        <Sidebar />
      </div>
    </html>
  );
}

// import React from "react";
// import Explorer from "./component/explorer/page";
// import Sidebar from "./component/sidebar/sidebar";
// import "./globals.css";

// const RootLayout = ({ children }) => {
//   return (
//     <div className="root-layout flex">
//       <Sidebar />
//       <div className="content-wrapper">{children}</div>
//       <Explorer />
//     </div>
//   );
// };

// export default RootLayout;
